version: '{build}'

environment:

  matrix:

  - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
    VCVARS_SCRIPT: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat"
    VCVARS_PLATFORM: x86

init:

  - cmd: echo '"%VCVARS_SCRIPT%" %VCVARS_PLATFORM%'
  - cmd: '"%VCVARS_SCRIPT%" %VCVARS_PLATFORM%'

build_script:

  - cmd: |
      sed -i "s/ABC_USE_PTHREADS/ABC_DONT_USE_PTHREADS/g" *.dsp
      sed -i "s/SOURCE=..src.aig.uap.*//g" *.dsp
      unix2dos *.dsp

  - cmd: |
      appveyor PushArtifact abcspace.dsw
      appveyor PushArtifact abclib.dsp
      appveyor PushArtifact abcexe.dsp

  - cmd: |
      devenv abcspace.dsw /upgrade || dir
      appveyor PushArtifact UpgradeLog.htm
      msbuild abcspace.sln /m /nologo /p:Configuration=Release
