language: c++

matrix:
  include:

    - os: linux
      addons:
        apt:
          packages:
            - libreadline-dev

    - os: osx
      osx_image: xcode9
      before_install:
        - brew install readline

script:
  - make -j2
