version: '{build}'

environment:

  matrix:

  - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
    VCVARS_SCRIPT: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat"
    VCVARS_PLATFORM: x86

init:

  - cmd: '"%VCVARS_SCRIPT%" %VCVARS_PLATFORM%'


build_script:

  - cmd: dir
  - cmd: set
  - cmd: devenv abcspace.dsw /upgrade ; exit 0
  - cmd: devenv abcspace.sln /build
